const content={
 pt:{
  research:[
{image:'i simposio.jpeg',position:'foto-i-simposio',year:'2025',title:'I Simpósio de Desenvolvimento e Inovação Municipal',text:'Reuniu pesquisadores, gestores públicos e estudantes para debater inovação e políticas públicas.',link:'https://photos.app.goo.gl/iJuKuWetX7RrBFbK6'},
{image:'semana juridica.jpeg',position:'foto-semana-juridica',year:'2025',title:'Semana Jurídica',text:'Promoveu palestras sobre temas atuais do Direito, aproximando os alunos aos profissionais da área.',link:'https://photos.app.goo.gl/QfM3SJvfwNCUQBUz7'},
{image:'jornada de ia.jpeg',position:'foto-jornada-ia',year:'2026',title:'I Jornada de Inteligência Artificial e Direito',text:'Debateu os impactos da inteligência artificial na prática jurídica e na pesquisa sobre o Direito.',link:'https://photos.app.goo.gl/YeHEiL1etEV5baaU8'},
{image:'ii simposio.jpeg',position:'foto-ii-simposio',year:'2026',title:'II Simpósio de Desenvolvimento e Inovação Municipal',text:'Consolidou o simpósio como um espaço de diálogo interdisciplinar sobre inovação e gestão pública.',link:'https://photos.app.goo.gl/xwyf3LpdM5vNji8HA'}
],
  projects:[
   {id:1,area:'constitucional',icon:'fa-scale-balanced',status:'Em andamento',title:'Direitos fundamentais na era digital',text:'Mapeamento dos impactos de plataformas digitais sobre liberdade, privacidade e cidadania.',period:'2026–2027',team:'6 pesquisadores',details:'O projeto analisa conflitos entre inovação tecnológica, direitos fundamentais e responsabilização de plataformas. Prevê revisão bibliográfica, estudos de caso e produção de artigo coletivo.'},
   {id:2,area:'tecnologia',icon:'fa-shield-halved',status:'Em andamento',title:'LGPD e instituições de ensino',text:'Boas práticas de proteção de dados em ambientes acadêmicos e de pesquisa.',period:'2026',team:'4 pesquisadores',details:'Pesquisa aplicada para identificar riscos, deveres e práticas de governança de dados em instituições de ensino superior.'},
   {id:3,area:'sociedade',icon:'fa-city',status:'Planejamento',title:'Cidadania e acesso à justiça',text:'Análise de barreiras sociais e institucionais no acesso a direitos.',period:'2026–2028',team:'5 pesquisadores',details:'Estudo interdisciplinar sobre acesso à justiça, linguagem jurídica, desigualdade informacional e políticas de atendimento ao cidadão.'},
   {id:4,area:'tecnologia',icon:'fa-robot',status:'Concluído',title:'Inteligência artificial e autoria',text:'Reflexões jurídicas sobre criação, titularidade e responsabilidade em sistemas generativos.',period:'2025',team:'3 pesquisadores',details:'Projeto concluído com produção de resumo expandido e apresentação em seminário acadêmico.'},
   {id:5,area:'constitucional',icon:'fa-building-columns',status:'Em andamento',title:'Jurisdição constitucional comparada',text:'Comparação entre modelos de controle constitucional e seus efeitos democráticos.',period:'2025–2026',team:'5 pesquisadores',details:'Análise comparada de decisões paradigmáticas e modelos institucionais de controle de constitucionalidade.'},
   {id:6,area:'sociedade',icon:'fa-comments',status:'Planejamento',title:'Linguagem simples no Direito',text:'Estratégias para comunicação jurídica mais clara, inclusiva e acessível.',period:'2027',team:'4 pesquisadores',details:'Iniciativa voltada à tradução de conteúdos jurídicos complexos e avaliação de compreensão por públicos diversos.'}
  ],
  publications:[
   {id:1,title:'Proteção de dados e autonomia informacional no ensino superior',authors:'Guilherme Rocha; Mirella Juvencio',type:'Artigo',year:'2026',theme:'LGPD'},
   {id:2,title:'Constitucionalismo digital e novos espaços de cidadania',authors:'Grupo Galileu',type:'Capítulo',year:'2026',theme:'Direito digital'},
   {id:3,title:'Acesso à justiça e linguagem jurídica acessível',authors:'Mirella Juvencio',type:'Resumo',year:'2025',theme:'Cidadania'},
   {id:4,title:'Arbitragem comercial e segurança jurídica',authors:'Guilherme Rocha',type:'Artigo',year:'2025',theme:'Arbitragem'},
   {id:5,title:'Inteligência artificial, autoria e responsabilidade civil',authors:'Grupo Galileu',type:'Artigo',year:'2024',theme:'Inteligência artificial'}
  ],
  members:[
{name:'Prof. Dr. Guilherme Rocha',role:'Orientador',bio:'Coordenador do Curso de Direito da Faculdade Galileu.',image:'Guilherme.png',lattes:'https://lattes.cnpq.br/5444414523142287'},
{name:'Mirella Juvêncio',role:'Assistente',bio:'Discente do 6º semestre do Curso de Direito da Faculdade Galileu.',image:'Mirella.jpg',lattes:'https://lattes.cnpq.br/9581364049834006'},
{name:'Nathália Ribeiro',role:'Assistente',bio:'Discente do 7º semestre do Curso de Direito da Faculdade Galileu.',image:'Nathalia.jpg',lattes:'https://lattes.cnpq.br/0788925273698208'},
  ],
  events:[
   {title:'Encontro de pesquisa: Constitucionalismo digital',date:'2026-08-12',time:'19:00',location:'Sala de Metodologias Ativas',type:'Grupo de estudo'},
   {title:'Oficina de escrita científica',date:'2026-08-28',time:'18:30',location:'Laboratório acadêmico',type:'Oficina'},
   {title:'Seminário Direito, IA e Sociedade',date:'2026-09-19',time:'09:00',location:'Auditório principal',type:'Seminário'},
   {title:'Prazo para submissão de resumos',date:'2026-10-02',time:'23:59',location:'Envio eletrônico',type:'Edital'}
  ],
  news:[
   {icon:'fa-trophy',date:'22 jul. 2026',title:'Grupo seleciona trabalhos para seminário científico',text:'Produções de estudantes serão apresentadas no próximo encontro acadêmico.'},
   {icon:'fa-file-circle-plus',date:'10 jul. 2026',title:'Chamada aberta para novos integrantes',text:'Estudantes interessados podem enviar manifestação pelo formulário do portal.'},
   {icon:'fa-handshake',date:'28 jun. 2026',title:'Nova frente de colaboração interdisciplinar',text:'O grupo amplia o diálogo com áreas de tecnologia, educação e políticas públicas.'}
  ]
 },
 en:{
  research:[
   {icon:'fa-landmark',title:'Constitutional Law and Citizenship',text:'Fundamental rights, democracy, institutions and civic participation.',topics:['Constitution','Democracy','Citizenship']},
   {icon:'fa-fingerprint',title:'Technology and Intellectual Property',text:'Data protection, artificial intelligence, innovation and new regulatory frameworks.',topics:['Data protection','AI','Innovation']},
   {icon:'fa-people-group',title:'Law, Society and Public Policy',text:'Relationships among legal rules, inequality, public policy and social transformation.',topics:['Public policy','Inclusion','Society']}
  ],
  projects:[
   {id:1,area:'constitucional',icon:'fa-scale-balanced',status:'In progress',title:'Fundamental rights in the digital age',text:'Mapping how digital platforms affect freedom, privacy and citizenship.',period:'2026–2027',team:'6 researchers',details:'The project examines conflicts among technological innovation, fundamental rights and platform accountability. It includes a literature review, case studies and a collaborative article.'},
   {id:2,area:'tecnologia',icon:'fa-shield-halved',status:'In progress',title:'Data protection and educational institutions',text:'Good data-protection practices in academic and research environments.',period:'2026',team:'4 researchers',details:'Applied research to identify risks, duties and data-governance practices in higher-education institutions.'},
   {id:3,area:'sociedade',icon:'fa-city',status:'Planning',title:'Citizenship and access to justice',text:'An analysis of social and institutional barriers to accessing rights.',period:'2026–2028',team:'5 researchers',details:'An interdisciplinary study of access to justice, legal language, information inequality and citizen-service policies.'},
   {id:4,area:'tecnologia',icon:'fa-robot',status:'Completed',title:'Artificial intelligence and authorship',text:'Legal perspectives on creation, ownership and liability in generative systems.',period:'2025',team:'3 researchers',details:'A completed project that produced an extended abstract and a presentation at an academic seminar.'},
   {id:5,area:'constitucional',icon:'fa-building-columns',status:'In progress',title:'Comparative constitutional jurisdiction',text:'A comparison of constitutional-review models and their democratic effects.',period:'2025–2026',team:'5 researchers',details:'Comparative analysis of landmark decisions and institutional models of constitutional review.'},
   {id:6,area:'sociedade',icon:'fa-comments',status:'Planning',title:'Plain language in law',text:'Strategies for clearer, more inclusive and accessible legal communication.',period:'2027',team:'4 researchers',details:'An initiative focused on translating complex legal content and evaluating comprehension among diverse audiences.'}
  ],
  publications:[
   {id:1,title:'Data protection and informational autonomy in higher education',authors:'Guilherme Rocha; Mirella Juvencio',type:'Article',year:'2026',theme:'Data protection'},
   {id:2,title:'Digital constitutionalism and new spaces for citizenship',authors:'Galileu Group',type:'Book chapter',year:'2026',theme:'Digital law'},
   {id:3,title:'Access to justice and accessible legal language',authors:'Mirella Juvencio',type:'Abstract',year:'2025',theme:'Citizenship'},
   {id:4,title:'Commercial arbitration and legal certainty',authors:'Guilherme Rocha',type:'Article',year:'2025',theme:'Arbitration'},
   {id:5,title:'Artificial intelligence, authorship and civil liability',authors:'Galileu Group',type:'Article',year:'2024',theme:'Artificial intelligence'}
  ],
  members:[
   {name:'Dr. Guilherme Rocha',role:'Faculty researcher',bio:'Research in treaty law, commercial arbitration and legal studies.',image:'Guilherme.png'},
   {name:'Mirella Juvencio',role:'Student researcher',bio:'Interests in hermeneutics, constitutional procedure and undergraduate research.',image:'Mirella.png'},
   {name:'Guest researcher',role:'Associate researcher',bio:'Reserved for faculty members, students and academic partners.',image:null}
  ],
  events:[
   {title:'Research meeting: Digital constitutionalism',date:'2026-08-12',time:'19:00',location:'Active Learning Room',type:'Study group'},
   {title:'Scientific writing workshop',date:'2026-08-28',time:'18:30',location:'Academic laboratory',type:'Workshop'},
   {title:'Law, AI and Society Seminar',date:'2026-09-19',time:'09:00',location:'Main auditorium',type:'Seminar'},
   {title:'Abstract submission deadline',date:'2026-10-02',time:'23:59',location:'Online submission',type:'Call for papers'}
  ],
  news:[
   {icon:'fa-trophy',date:'Jul 22, 2026',title:'Group selects papers for scientific seminar',text:'Student work will be presented at the next academic meeting.'},
   {icon:'fa-file-circle-plus',date:'Jul 10, 2026',title:'Open call for new members',text:'Interested students can apply through the portal form.'},
   {icon:'fa-handshake',date:'Jun 28, 2026',title:'New interdisciplinary collaboration initiative',text:'The group expands its dialogue with technology, education and public-policy fields.'}
  ]
 }
};

const ui={
 en:{
 'Ir para o conteúdo':'Skip to content','Grupo de Pesquisa':'Research Group','Sobre':'About','Pesquisas':'Research','Projetos':'Projects','Publicações':'Publications','Equipe':'Team','Agenda':'Agenda','Participar':'Join',
 'Núcleo de Estudos Jurídicos':'Center for Legal Studies','Pesquisa que transforma conhecimento em impacto.':'Research that turns knowledge into impact.','Um ecossistema acadêmico de investigação, colaboração e produção científica dedicado aos desafios contemporâneos do Direito e da sociedade.':'An academic ecosystem for investigation, collaboration and scientific production focused on contemporary challenges in law and society.','Explorar projetos':'Explore projects','Quero participar':'Join the group','Pesquisa interdisciplinar':'Interdisciplinary research','Iniciação científica':'Undergraduate research','Extensão acadêmica':'Academic outreach',
 'Projetos desenvolvidos':'Projects developed','Produções científicas':'Scientific outputs','Pesquisadores':'Researchers','Eventos realizados':'Events held','Sobre o grupo':'About the group','Conhecimento jurídico com rigor, inovação e relevância social.':'Legal knowledge with rigor, innovation and social relevance.','O Grupo de Pesquisa Galileu conecta docentes, estudantes e pesquisadores para investigar transformações jurídicas, incentivar a iniciação científica e aproximar a academia dos desafios reais da sociedade.':'The Galileu Research Group connects faculty, students and researchers to investigate legal transformations, foster undergraduate research and bring academia closer to real social challenges.','O portal reúne projetos, publicações, eventos, oportunidades, dados de impacto e canais de colaboração em um único ambiente.':'The portal brings together projects, publications, events, opportunities, impact data and collaboration channels in one place.','Formação':'Education','Pesquisa':'Research','Extensão':'Outreach','Rigor científico':'Scientific rigor','Método, evidências, ética e responsabilidade acadêmica.':'Method, evidence, ethics and academic responsibility.','Inovação aplicada':'Applied innovation','Estudos voltados a problemas jurídicos contemporâneos.':'Studies focused on contemporary legal issues.','Impacto social':'Social impact','Conhecimento capaz de gerar diálogo e transformação.':'Knowledge that fosters dialogue and transformation.',
 'Eixos de investigação':'Research areas','Linhas de pesquisa':'Research lines','Temas que orientam estudos, projetos, publicações e atividades do grupo.':'Themes guiding the group’s studies, projects, publications and activities.','Pesquisa em desenvolvimento':'Research in progress','Acompanhe objetivos, etapas, equipes e resultados dos projetos ativos.':'Follow the goals, stages, teams and results of active projects.','Propor parceria':'Propose a partnership','Todas as áreas':'All areas','Constitucional':'Constitutional law','Tecnologia':'Technology','Sociedade':'Society',
 'Biblioteca científica':'Scientific library','Publicações e produções':'Publications and outputs','Artigos, capítulos, resumos e materiais acadêmicos organizados para consulta.':'Articles, chapters, abstracts and academic materials organized for consultation.','Todos os anos':'All years','Todos os formatos':'All formats','Artigos':'Articles','Capítulos':'Book chapters','Resumos':'Abstracts','Nenhuma publicação encontrada com esses filtros.':'No publications were found with these filters.',
 'Pessoas':'People','Pesquisadores que movem o conhecimento':'Researchers who advance knowledge','Perfis acadêmicos, áreas de atuação e formas de contato.':'Academic profiles, fields of expertise and contact channels.','Impacto acadêmico':'Academic impact','Resultados que ultrapassam a sala de aula.':'Results that go beyond the classroom.','O grupo incentiva autoria, protagonismo estudantil, colaboração interdisciplinar e circulação pública do conhecimento.':'The group encourages authorship, student leadership, interdisciplinary collaboration and public circulation of knowledge.','Ver produções':'View outputs','Produção científica':'Scientific output','Participação estudantil':'Student participation','Projetos interdisciplinares':'Interdisciplinary projects','Atividades de extensão':'Outreach activities',
 'Agenda acadêmica':'Academic calendar','Próximas atividades':'Upcoming activities','Nossos encontros explorarão as contribuições da Psicologia para a compreensão da política, da democracia e das relações sociais. Aqui você encontrará as leituras recomendadas e, ao longo das próximas semanas, os registros de cada encontro.':'Our meetings will explore psychology’s contributions to understanding politics, democracy and social relations. Here you will find the recommended readings and, over the coming weeks, the records of each meeting.','Baixar agenda':'Download calendar','Atualizações':'Updates','Notícias e oportunidades':'News and opportunities','O que está acontecendo no Grupo Galileu.':'What is happening in the Galileu Group.','Rede de colaboração':'Collaboration network','Instituições e parceiros':'Institutions and partners','Núcleo Jurídico':'Legal Center','Iniciação Científica':'Undergraduate Research','Extensão Universitária':'University Outreach','Comunidade Acadêmica':'Academic Community',
 'Faça parte':'Join us','Comece sua trajetória na pesquisa.':'Start your research journey.','Envie seu interesse para participar dos encontros, integrar projetos ou propor uma parceria acadêmica.':'Submit your interest to attend meetings, join projects or propose an academic partnership.','Contato direto com a coordenação':'Direct contact with the coordination team','Possibilidade de iniciação científica':'Undergraduate research opportunities','Participação em eventos e publicações':'Participation in events and publications','Nome completo':'Full name','E-mail':'Email','Curso':'Degree program','Semestre':'Semester','Área de interesse':'Area of interest','Direito Constitucional':'Constitutional Law','Tecnologia e Direito':'Technology and Law','Sociedade e Cidadania':'Society and Citizenship','Outra área':'Other area','Conte um pouco sobre seu interesse':'Tell us about your interest','Autorizo o uso dos dados para retorno deste contato.':'I authorize the use of my data to respond to this inquiry.','Enviar interesse':'Submit interest',
 'Boletim Galileu':'Galileu Newsletter','Receba novidades acadêmicas.':'Receive academic updates.','Publicações, eventos e oportunidades diretamente no seu e-mail.':'Publications, events and opportunities delivered to your inbox.','Inscrever-se':'Subscribe','Pesquisa, formação acadêmica e impacto social por meio do conhecimento jurídico.':'Research, academic education and social impact through legal knowledge.','Navegação':'Navigation','Contato':'Contact','Área de gestão':'Content management','Privacidade · Acessibilidade · Ética em pesquisa':'Privacy · Accessibility · Research ethics','Grupo de Pesquisa Galileu.':'Galileu Research Group.',
 'Pesquisa global':'Global search','O que você procura?':'What are you looking for?','Gestão local':'Local management','Painel de conteúdo':'Content dashboard','Este painel demonstrativo salva alterações neste navegador.':'This demo dashboard saves changes in this browser.','Nova publicação':'New publication','Novo evento':'New event','Artigo':'Article','Capítulo':'Book chapter','Resumo':'Abstract','Adicionar publicação':'Add publication','Adicionar evento':'Add event','Restaurar dados originais':'Restore original data'
 },
 placeholders:{en:{'Buscar projeto':'Search projects','Buscar por título, autor ou tema':'Search by title, author or topic','Ex.: 4º semestre':'E.g. 4th semester','seuemail@exemplo.com':'you@example.com','Projetos, publicações, pesquisadores...':'Projects, publications, researchers...','Título':'Title','Autores':'Authors','Tema':'Topic','Nome do evento':'Event name','Local ou link':'Location or link'}},
 aria:{en:{'Início do Grupo Galileu':'Galileu Group home','Navegação principal':'Main navigation','Abrir pesquisa':'Open search','Alternar idioma':'Switch language','Alternar tema':'Switch theme','Abrir menu':'Open menu','Indicadores do grupo':'Group indicators','Filtrar projetos':'Filter projects','Filtrar por ano':'Filter by year','Filtrar por tipo':'Filter by type','Fechar':'Close','Voltar ao topo':'Back to top'}}
};

const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem('galileu_'+k)||JSON.stringify(d))}catch{return structuredClone(d)}},set:(k,v)=>localStorage.setItem('galileu_'+k,JSON.stringify(v))};
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
let lang='pt';
let publications=store.get('publications',content.pt.publications),events=store.get('events',content.pt.events);
const originalText=new WeakMap(),originalAttrs=new WeakMap();

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function t(pt,en){return lang==='en'?en:pt}
function localizedSaved(items,kind){if(lang==='pt')return items;return items.map(item=>{const basePt=content.pt[kind].find(x=>x.id===item.id||x.title===item.title);const baseEn=basePt&&content.en[kind].find(x=>x.id===basePt.id);return baseEn?{...item,...baseEn}:item})}
function captureStatic(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement?.closest('script,style'))continue;const v=n.nodeValue.trim();if(v)originalText.set(n,v)}$$('[placeholder],[aria-label],[title]').forEach(el=>{originalAttrs.set(el,{placeholder:el.getAttribute('placeholder'),aria:el.getAttribute('aria-label'),title:el.getAttribute('title')})})}
function applyStaticLanguage(){
 document.documentElement.lang=lang==='en'?'en':'pt-BR';document.title=lang==='en'?'Galileu Research Group | Academic Portal':'Grupo de Pesquisa Galileu | Portal Acadêmico';
 originalText.forEach?.(()=>{});
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement?.closest('script,style'))continue;const original=originalText.get(n);if(!original)continue;const value=lang==='en'?(ui.en[original]||original):original;n.nodeValue=n.nodeValue.replace(n.nodeValue.trim(),value)}
 $$('[placeholder],[aria-label],[title]').forEach(el=>{const o=originalAttrs.get(el);if(!o)return;if(o.placeholder)el.setAttribute('placeholder',o.placeholder);if(o.aria)el.setAttribute('aria-label',o.aria);if(o.title)el.setAttribute('title',o.title)});
}
function renderAll(){renderResearch();renderProjects();renderPublications();renderTeam();renderEvents();renderNews();}
function renderResearch(){const data=content[lang].research;const grid=$('#researchGrid');if(!grid)return;grid.innerHTML=data.map(r=>`<article class="research-card reveal visible"><img src="${r.image}" alt="${r.title}" class="research-image ${r.position}"><div class="research-content"><span class="member-role">${r.year}</span><h3>${r.title}</h3><p>${r.text}</p><a href="${r.link}" target="_blank" rel="noopener" class="card-action"><i class="fa-solid Fotos do evento"></i>Fotos do Evento</a></div></article>`).join('')}
function renderProjects(){const search=$('#projectSearch'),filter=$('#projectFilter'),grid=$('#projectGrid');if(!search||!filter||!grid)return;const q=(search.value||'').toLocaleLowerCase(),f=filter.value;const list=content[lang].projects.filter(p=>(f==='all'||p.area===f)&&(`${p.title} ${p.text}`.toLocaleLowerCase().includes(q)));grid.innerHTML=list.map(p=>`<article class="project-card"><div class="project-cover"><i class="fa-solid ${p.icon}"></i><span class="status">${p.status}</span></div><div class="project-body"><h3>${p.title}</h3><p>${p.text}</p><div class="project-meta"><span><i class="fa-regular fa-calendar"></i> ${p.period}</span><span><i class="fa-solid fa-users"></i> ${p.team}</span></div></div><button class="card-action" data-project="${p.id}">${t('Ver detalhes','View details')} <i class="fa-solid fa-arrow-right"></i></button></article>`).join('')||`<div class="empty-state"><p>${t('Nenhum projeto encontrado.','No projects found.')}</p></div>`;$$('[data-project]').forEach(b=>b.onclick=()=>openProject(+b.dataset.project))}
function renderPublications(){const q=($('#publicationSearch').value||'').toLocaleLowerCase(),y=$('#yearFilter').value,type=$('#typeFilter').value;let data=localizedSaved(publications,'publications');const typeMap={Artigo:'Article',Capítulo:'Book chapter',Resumo:'Abstract'};const selected=lang==='en'?(typeMap[type]||type):type;const list=data.filter(p=>(y==='all'||p.year===y)&&(type==='all'||p.type===selected)&&(`${p.title} ${p.authors} ${p.theme}`.toLocaleLowerCase().includes(q)));$('#publicationEmpty').hidden=!!list.length;$('#publicationList').innerHTML=list.map(p=>`<article class="publication-item"><div class="publication-year">${p.year}</div><div><h3>${p.title}</h3><p>${p.authors}</p><div class="publication-tags"><span>${p.type}</span><span>${p.theme||t('Pesquisa','Research')}</span></div></div><div class="publication-actions"><button class="small-btn" title="${t('Copiar referência','Copy citation')}" data-copy="${p.id}"><i class="fa-regular fa-copy"></i></button><button class="small-btn" title="${t('Visualizar','View')}" data-pub="${p.id}"><i class="fa-solid fa-arrow-up-right-from-square"></i></button></div></article>`).join('');$$('[data-copy]').forEach(b=>b.onclick=()=>copyCitation(+b.dataset.copy));$$('[data-pub]').forEach(b=>b.onclick=()=>openPublication(+b.dataset.pub))}
function renderTeam(){const data=content[lang].members;$('#teamGrid').innerHTML=data.map(m=>`<article class="member-card">${m.image?`<div class="member-image-wrapper"><img src="${m.image}" alt="${m.name}" class="${m.position||''}" loading="lazy" onerror="this.closest('.member-image-wrapper').classList.add('image-error');this.remove()"></div>`:`<div class="member-image-wrapper member-placeholder"><i class="fa-solid fa-user-graduate"></i></div>`}<div class="member-info"><span class="member-role">${m.role}</span><h3>${m.name}</h3><p>${m.bio}</p><div class="member-links"><a href="${m.lattes}" target="_blank" rel="noopener">Lattes</a></div></div></article>`).join('')}
function renderEvents(){const timeline=$('#eventTimeline');if(!timeline)return;const data=localizedSaved(events,'events');const months=lang==='en'?['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']:['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];data.sort((a,b)=>a.date.localeCompare(b.date));timeline.innerHTML=data.map(e=>{const d=new Date(e.date+'T12:00:00');return `<article class="event-item"><div class="event-date"><strong>${String(d.getDate()).padStart(2,'0')}</strong><span>${months[d.getMonth()]}</span></div><div class="event-info"><h3>${e.title}</h3><p><i class="fa-regular fa-clock"></i> ${e.time||t('A definir','TBD')} &nbsp; <i class="fa-solid fa-location-dot"></i> ${e.location||t('A definir','TBD')}</p></div><span class="event-type">${e.type}</span></article>`}).join('')}
function renderNews(){$('#newsGrid').innerHTML=content[lang].news.map(n=>`<article class="news-card"><div class="news-thumb"><i class="fa-solid ${n.icon}"></i></div><div><time>${n.date}</time><h3>${n.title}</h3><p>${n.text}</p></div></article>`).join('')}
function openModal(html){$('#modalContent').innerHTML=html;$('#detailModal').classList.add('open');$('#detailModal').setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeModals(){$$('.modal,.search-overlay').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')});document.body.classList.remove('no-scroll')}
function openProject(id){const p=content[lang].projects.find(x=>x.id===id);openModal(`<div class="modal-detail"><span class="section-kicker">${p.status}</span><h2>${p.title}</h2><p>${p.details}</p><div class="topic-list"><span>${p.period}</span><span>${p.team}</span><span>${p.area}</span></div><a class="btn btn-primary" href="#participar" onclick="document.querySelector('.modal-close').click()">${t('Demonstrar interesse','Express interest')}</a></div>`)}
function getPub(id){return localizedSaved(publications,'publications').find(x=>x.id===id)}
function openPublication(id){const p=getPub(id);openModal(`<div class="modal-detail"><span class="section-kicker">${p.type} · ${p.year}</span><h2>${p.title}</h2><p><strong>${t('Autores','Authors')}:</strong> ${p.authors}</p><p><strong>${t('Tema','Topic')}:</strong> ${p.theme}</p><p>${t('Registro demonstrativo. Neste espaço podem ser inseridos resumo, DOI, periódico, palavras-chave e arquivo para download.','Demo record. This area can include an abstract, DOI, journal, keywords and a downloadable file.')}</p><button class="btn btn-primary" id="copyModalTitle">${t('Copiar título','Copy title')}</button></div>`);$('#copyModalTitle').onclick=()=>navigator.clipboard.writeText(p.title).then(()=>toast(t('Título copiado.','Title copied.')))}
function copyCitation(id){const p=getPub(id);navigator.clipboard.writeText(`${p.authors}. ${p.title}. ${p.year}.`).then(()=>toast(t('Referência copiada.','Citation copied.')))}
function initSearch(){const all=()=>[...content[lang].projects.map(x=>({type:t('Projeto','Project'),kind:'project',title:x.title,text:x.text,id:x.id})),...localizedSaved(publications,'publications').map(x=>({type:t('Publicação','Publication'),kind:'publication',title:x.title,text:x.authors,id:x.id})),...content[lang].members.map(x=>({type:t('Pesquisador','Researcher'),kind:'member',title:x.name,text:x.bio}))];$('#globalSearch').oninput=e=>{const q=e.target.value.toLocaleLowerCase();const list=q?all().filter(x=>(x.title+' '+x.text).toLocaleLowerCase().includes(q)).slice(0,12):[];$('#globalResults').innerHTML=list.map(x=>`<button class="global-result" data-kind="${x.kind}" data-id="${x.id||''}"><strong>${x.title}</strong><br><small>${x.type} · ${x.text}</small></button>`).join('')||`<p class="muted">${t('Digite para pesquisar no portal.','Type to search the portal.')}</p>`;$$('.global-result').forEach(r=>r.onclick=()=>{closeModals();if(r.dataset.kind==='project')openProject(+r.dataset.id);if(r.dataset.kind==='publication')openPublication(+r.dataset.id)})}}
function downloadCalendar(){const data=localizedSaved(events,'events'),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Grupo Galileu//Agenda//PT-BR'];data.forEach(e=>{const dt=e.date.replaceAll('-','')+'T'+(e.time||'09:00').replace(':','')+'00';lines.push('BEGIN:VEVENT',`DTSTART:${dt}`,`SUMMARY:${e.title}`,`LOCATION:${e.location||''}`,'END:VEVENT')});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='agenda-grupo-galileu.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function initAdmin(){$$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button').forEach(x=>x.classList.remove('active'));$$('.admin-form').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#publicationAdmin').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));publications.unshift({id:Date.now(),...d,year:String(d.year)});store.set('publications',publications);renderPublications();e.target.reset();toast(t('Publicação adicionada.','Publication added.'))};$('#eventAdmin').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));events.push({...d,type:'Evento'});store.set('events',events);renderEvents();e.target.reset();toast(t('Evento adicionado.','Event added.'))};$('#resetData').onclick=()=>{localStorage.removeItem('galileu_publications');localStorage.removeItem('galileu_events');publications=structuredClone(content.pt.publications);events=structuredClone(content.pt.events);renderPublications();renderEvents();toast(t('Dados originais restaurados.','Original data restored.'))}}
function initUI(){const nav=$('.navbar'),toggle=$('.menu-toggle'),links=$('.nav-links');const onScroll=()=>{nav.classList.toggle('scrolled',scrollY>20);$('#backToTop').classList.toggle('show',scrollY>600);const h=Math.max(1,document.documentElement.scrollHeight-innerHeight);$('.reading-progress span').style.width=Math.min(100,scrollY/h*100)+'%'};addEventListener('scroll',onScroll,{passive:true});onScroll();toggle.onclick=()=>{const o=links.classList.toggle('open');toggle.classList.toggle('active',o);toggle.setAttribute('aria-expanded',o)};$$('.nav-links a').forEach(a=>a.onclick=()=>{links.classList.remove('open');toggle.setAttribute('aria-expanded','false')});const savedTheme=localStorage.getItem('galileu_theme')||'light';document.documentElement.dataset.theme=savedTheme;$('#searchOpen').onclick=()=>{$('#searchOverlay').classList.add('open');$('#searchOverlay').setAttribute('aria-hidden','false');document.body.classList.add('no-scroll');setTimeout(()=>$('#globalSearch').focus(),80)};$('#searchClose').onclick=closeModals;$$('.modal-close').forEach(b=>b.onclick=closeModals);$$('.modal,.search-overlay').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});$('#adminOpen').onclick=()=>{$('#adminModal').classList.add('open');$('#adminModal').setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')};$('#backToTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});const calendarBtn=$('#calendarDownload');if(calendarBtn)calendarBtn.onclick=downloadCalendar;$('#year').textContent=new Date().getFullYear()}
function initForms(){$('#joinForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));localStorage.setItem('galileu_last_interest',JSON.stringify(data));$('#formStatus').textContent=t('Interesse registrado com sucesso. O formulário está pronto para integração com e-mail ou banco de dados.','Your interest was registered successfully. The form is ready for email or database integration.');e.target.reset();toast(t('Interesse enviado com sucesso.','Interest submitted successfully.'))};$('#newsletterForm').onsubmit=e=>{e.preventDefault();toast(t('Inscrição realizada.','Subscription completed.'));e.target.reset()}}
function initObservers(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(el=>o.observe(el));const statsO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('[data-count]').forEach(n=>{let v=0,target=+n.dataset.count;const timer=setInterval(()=>{v++;n.textContent=String(v).padStart(2,'0');if(v>=target)clearInterval(timer)},35)});statsO.disconnect()}}));statsO.observe($('.stats'))}
document.addEventListener('DOMContentLoaded',()=>{captureStatic();applyStaticLanguage();renderAll();initSearch();initAdmin();initUI();initForms();initObservers();['projectSearch','projectFilter'].forEach(id=>$('#'+id).addEventListener('input',renderProjects));['publicationSearch','yearFilter','typeFilter'].forEach(id=>$('#'+id).addEventListener('input',renderPublications))});
